name: Build and Analyze

on:
  push:
    branches: [ "main", "master", "feature/testing-suite" ] # Branch triggers
  pull_request:
    branches: [ "main", "master", "feature/testing-suite" ] # Branch triggers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Importante per Sonar e analisi corrette

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Configurazione report JaCoCo
    - name: Build and Test with Maven
      run: mvn -B clean verify jacoco:report

    # Configurazione CodeCov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./target/site/jacoco/jacoco.xml
        fail_ci_if_error: true